const artworks = [
  {
    id: 0,
    title: "Nostalgic Beauty",
    artist: "Badejo Abiodun",
    published: "2020",
    medium: "Painting",
    material: "Canvas",
    category: "Comtemporary Art",
    subject: "Portraiture",
    style: "Conceptual",
    description:
      "Nostalgic Beauty is a painting on canvas that embodies creativity and beauty.",
    keywords: ["feminine", "modern", "blue"],
    price: 1500000,
    dimensions: { width: 15, height: 10, depth: 0.1 },
    images: [
      "http://www.imageurl.com/image1",
      "http://www.imageurl.com/image2",
      "http://www.imageurl.com/image3",
    ],
    editions: "Limited edition",
    availability: "For sale",
  },
  {
    id: 1,
    title: "Boss Lady II",
    artist: "Tolu Aliki",
    published: "2019",
    medium: "Painting",
    material: "Canvas",
    category: "Comtemporary Art",
    subject: "Portraiture",
    style: "Conceptual",
    description:
      "Boss Lady II is a painting on canvas that embodies creativity and beauty.",
    keywords: ["feminine", "modern", "blue"],
    price: 3318000,
    dimensions: { width: 15, height: 10, depth: 0.1 },
    images: [
      "http://www.imageurl.com/image1",
      "http://www.imageurl.com/image2",
      "http://www.imageurl.com/image3",
    ],
    editions: "Limited edition",
    availability: "For sale",
  },
  {
    id: 2,
    title: "Hope",
    artist: "Cornelius Browne",
    published: "2019",
    medium: "Print",
    material: "Canvas",
    category: "Modern Art",
    subject: "Portraiture",
    style: "Digital",
    description:
      "Hope is a print on canvas that embodies creativity and beauty.",
    keywords: ["feminine", "modern", "blue"],
    price: 3318000,
    dimensions: { width: 15, height: 10, depth: 0.1 },
    images: [
      "http://www.imageurl.com/image1",
      "http://www.imageurl.com/image2",
      "http://www.imageurl.com/image3",
    ],
    editions: "Limited edition",
    availability: "For sale",
  },
];

module.exports = artworks;
