const artworks = [
  {
    id: 0,
    title: "When we were young",
    artist: "Oladipupo Adesina",
    dimensions: "119.38cm x 91.44cm",
    medium: "Painting on canvas",
    price: "3,318,000",
    year: "2020",
    url: "./when-we-were-young.png",
  },
  {
    id: 1,
    title: "Traditional Dancer",
    artist: "Uche Edozie",
    dimensions: "119.38cm x 91.44cm",
    medium: "Photography",
    price: "3,318,000",
    year: "2019",
    url: "./traditional-dancer.png",
  },
  {
    id: 2,
    title: "Gaze of Hope",
    artist: "Durodola Yusuf",
    dimensions: "119.38cm x 91.44cm",
    medium: "Canvas on stretcher",
    price: "3,318,000",
    year: "2019",
    url: "./gaze-of-hope.png",
  },
  {
    id: 3,
    title: "Our Neighbourhood",
    artist: "Divine Effiong",
    dimensions: "119.38cm x 91.44cm",
    medium: "Painting on canvas",
    price: "3,318,000",
    year: "2022",
    url: "./our-neighbourhood.png",
  },
  {
    id: 4,
    title: "Nolstagia Beauty I",
    artist: "Uzoma Samuel",
    dimensions: "119.38cm x 91.44cm",
    medium: "Print on canvas",
    price: "3,318,000",
    year: "2020",
    url: "./nostalgia-beauty.png",
  },
  {
    id: 5,
    title: "Boss Lady II",
    artist: "Tolu Aliki",
    dimensions: "119.38cm x 91.44cm",
    medium: "Canvas on stretcher",
    price: "3,318,000",
    year: "2019",
    url: "./boss-lady.png",
  },
  {
    id: 6,
    title: "Friends",
    artist: "Tola Wewe",
    dimensions: "119.38cm x 91.44cm",
    medium: "Painting on canvas",
    price: "1,777,500",
    year: "2021",
    url: "./friends.png",
  },
  {
    id: 7,
    title: "African Queen",
    artist: "Cornelius Browne",
    dimensions: "119.38cm x 91.44cm",
    medium: "Print on canvas",
    price: "547,650",
    year: "2019",
    url: "./african-queen.png",
  },
  //   {
  //     id: 8,
  //     title: "Purple House",
  //     artist: "Steve Ekpenisi",
  //     dimensions: "119.38cm x 91.44cm",
  //     medium: "Painting on canvas",
  //     price: "2,370,000",
  //     year: "2022",
  //     url: "./purple-house.png",
  //   },
  //   {
  //     id: 9,
  //     title: "Expression",
  //     artist: "Nelson Okoh",
  //     dimensions: "119.38cm x 91.44cm",
  //     medium: "Sculpture",
  //     price: "1,422,000",
  //     year: "2020",
  //     url: "./expression.png",
  //   },
];

const slides = [
  {
    id: 0,
    title: "When we were young",
    artist: "Oladipupo Adesina",
    dimensions: "119.38cm x 91.44cm",
    medium: "Painting on canvas",
    year: "2020",
    url: "./sliderImg0.png",
  },
  {
    id: 1,
    title: "Traditional Dancer",
    artist: "Uche Edozie",
    dimensions: "119.38cm x 91.44cm",
    medium: "Painting on canvas",
    year: "2019",
    url: "./sliderImg1.png",
  },
  {
    id: 2,
    title: "Gaze of Hope",
    artist: "Durodola Yusuf",
    dimensions: "119.38cm x 91.44cm",
    medium: "Canvas on stretcher",
    year: "2019",
    url: "./sliderImg2.png",
  },
  {
    id: 3,
    title: "Our Neighbourhood",
    artist: "Divine Effiong",
    dimensions: "119.38cm x 91.44cm",
    medium: "Painting on canvas",
    year: "2022",
    url: "./sliderImg3.png",
  },
  {
    id: 4,
    title: "Nolstagia Beauty I",
    artist: "Uzoma Samuel",
    dimensions: "119.38cm x 91.44cm",
    medium: "Painting on canvas",
    year: "2020",
    url: "./sliderImg4.png",
  },
];

const categories = [
  {
    id: 0,
    title: "Artworks",
    url: "./cat-artworks.png",
  },
  {
    id: 1,
    title: "Contemporary Art",
    url: "./cat-contemporary.png",
  },
  {
    id: 2,
    title: "Emerging Art",
    url: "./cat-emerging.png",
  },
  {
    id: 3,
    title: "Abstract Art",
    url: "./cat-abstract.png",
  },
  {
    id: 4,
    title: "Impressionist & Modern Art",
    url: "./cat-modern.png",
  },
  {
    id: 5,
    title: "Minimalism",
    url: "./cat-minimalism.png",
  },
  {
    id: 6,
    title: "Pop Art",
    url: "./cat-pop.png",
  },
  {
    id: 7,
    title: "Street Art",
    url: "./cat-street.png",
  },
];

export { artworks, slides, categories };
